using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Dhgms.DataManager.Model.Helper.Postcode
{
/*
"AB", "Aberdeen"
"AL", "St. Albans"
"B", "Birmingham"
"BA", "Bath"
"BB", "Blackburn"
"BD", "Bradford"
"BH", "Bournemouth"
"BL", "Bolton"
"BN", "Brighton"
"BR", "Bromley"
"BS", "Bristol"
"BT", "Belfast"
"CA", "Carlisle"
"CB", "Cambridge"
"CF", "Cardiff"
"CH", "Chester"
"CM", "Chelmsford"
"CO", "Colchester"
"CR", "Croydon"
"CT", "Canterbury"
"CV", "Coventry"
"CW", "Crewe"
"DA", "Dartford"
"DD", "Dundee"
"DE", "Derby"
"DG", "Dumfries"
"DH", "Durham"
"DL", "Darlington"
"DN", "Doncaster"
"DT", "Dorchester"
"DY", "Dudley"
"E", "London East"
"EC", "London East Central"
"EH", "Edinburgh"
"EN", "Enfield"
"EX", "Exeter"
"FK", "Falkirk"
"FY", "Fylde"
"G", "Glasgow"
"GL", "Gloucester"
"GU", "Guildford"
"GY", "Guernsey & Alderney"
"HA", "Harrow"
"HD", "Huddersfield"
"HG", "Harrogate"
"HP", "Hemel Hempstead"
"HR", "Hereford"
"HS", "HEBRIDES"
"HU", "Hull"
"HX", "Halifax"
"IG", "Ilford"
"IM", "Isle of Man"
"IP", "Ipswich"
"IV", "Inverness"
"JE", "Jersey"
"KA", "Kilmarnock"
"KT", "Kingston Upon Thames"
"KW", "Kirkwall"
"KY", "Kirkcaldy"
"L", "Liverpool"
"LA", "Lancaster"
"LD", "Llandrindod Wells"
"LE", "Leicester"
"LL", "Llandudno"
"LN", "Lincoln"
"LS", "Leeds"
"LU", "Luton"
"M", "Manchester"
"ME, "Medway"
"MK", "Milton Keynes"
"ML", "Motherwell"
"N", "London North"
"NE", "Newcastle on Tyne"
"NG", "Nottingham"
"NN", "Northampton"
"NP", "Newport"
"NR", "Norwich"
"NW", "London North West"
"OL", "Oldham"
"OX", "Oxford"
"PA", "Paisley"
"PE", "Peterborough"
"PH", "Perth"
"PL", "Plymouth"
"PO", "Portsmouth"
"PR", "Preston"
"RG", "Reading"
"RH", "Redhill"
"RM", "Romford"
"S", "Sheffield"
"SA", "Swansea"
"SE", "London South East"
"SG", "Stevenage"
"SK", "Stockport"
"SL", "Slough"
"SM", "Sutton"
"SN", "Swindon"
"SO", "Southampton"
"SP", "Salisbury"
"SR", "Sunderland"
"SS", "Southend on Sea"
"ST", "Stoke On Trent"
"SW", "London South West"
"SY", "Shrewsbury"
"TA", "Taunton"
"TD", "Berwick upon Tweed"
"TF", "Telford"
"TN", "Tunbridge Wells"
"TQ", "Torquay"
"TR", "Truro"
"TS", "Teesside"
"TW", "Twickenham"
"UB", "Uxbridge"
"W", "London West"
"WA", "Warrington"
"WC", "London West Central"
"WD", "Watford"
"WF", "Wakefield"
"WN", "Wigan"
"WR", "Worcester"
"WS", "Walsall"
"WV", "Wolverhampton"
"YO", "York"
"ZE", "Lerwick"
 */

    /*
    private static Dictionary<string, string> postAreaMappings = new Dictionary<string, string>
    {
    
    };

    class PostArea
    {
    }
     * */
}
